apiVersion: v1
kind: ReplicationController  
metadata:  
  name: koolearn-eureka-controller
spec:  
  replicas: 2                            
  selector:  
    name: eureka
  template:  
    metadata:  
      labels:
        name: eureka
    spec:  
      containers:  
        - name: koolearn-eureka
          image: registry.cn-hangzhou.aliyuncs.com/lvyangjun/koolearn-eureka:v1.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8111
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-nodeport
spec:
  ports:
    - port: 8111
      targetPort: 8111
  type: LoadBalancer
  selector:
    name: eureka