apiVersion: v1
kind: ReplicationController  
metadata:  
  name: koolearn-webapp-controller
spec:  
  replicas: 2                            
  selector:  
    name: webapp
  template:  
    metadata:  
      labels:
        name: webapp
    spec:  
      containers:  
        - name: koolearn-webapp
          image: registry.cn-hangzhou.aliyuncs.com/lvyangjun/koolearn-webapp:v1.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
  selector:
    name: webapp