apiVersion: v1
kind: ReplicationController  
metadata:  
  name: koolearn-service-controller
spec:  
  replicas: 2                            
  selector:  
    name: service
  template:  
    metadata:  
      labels:
        name: service
    spec:  
      containers:  
        - name: koolearn-service
          image: registry.cn-hangzhou.aliyuncs.com/lvyangjun/koolearn-service:v1.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    name: service